call func.createlogin('mash', 'pass');
call func.createach(2, 'Маша Рогатина Сергеевна', 483);
call func.creastud(1, 'Виноградова Дарья Андреевна', 484, '');
call func.addoc(1, 'военник', '');
call func.updatelogin(1, 'dasha');
call func.updatepassword(1, 'Passw');
call func.updateachidlogin(2, 2);
call func.updateachfio(2, 'Cаша Романовна Сергеевна' );
call func.updateachgroupa(1, 384);
call func.updateportfolfio(1, 'Бобр');
call func.updateportfolgroupa(1, 483);
call func.updateportfolphoto(1, '');
call func.updatedocidstud(2, 2);
call func.updatedocname(3, 'Билет');
call func.updatedocdoc(3, '');